apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "postal.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "postal.fullname" . }}
data:
  postal.yml: {{ toYaml .Values.config | b64enc | quote }}
  signing.key: {{ .Values.signingKey | b64enc | quote }}
